console.log("Loading options.js...");

const sdb = "https://steamdb.info/app/"; // Base URL for SteamDB links

const OPTIONS = [
  { text: "🕰️🌎❓Timeguessr🕰️🌎❓" },
  { text: "✅Scattergories🚫" },
  { text: "👑🏰King of the Castle👑🏰" },
  { text: "🕵️‍♂️Code Names🕵️‍♀️" },
  { text: "➡️⬇️Crossword➡️⬇️" },
  { text: "✏️🎨Drawful✏️🎨" },
  { text: "🤡Quiplash🤡" },
  { text: "⁉️🔪🩸🎉Trivia Murder Party⁉️🔪🩸🎉" },
  { text: "🤷‍♂️Blather Round🤷‍♂️" },
  { text: "❓Ryan Picks a Random Quiz❓" },
  { text: "🧩Those New Puzzles Will Found🧩" },
  { text: "✨✨✨Try The New Thing Someone Just Suggested!✨✨✨" },
  //Steam Options
  { text: "🤿🌊Murky Divers🤿🌊", 
    link: sdb + "2963880" },
  { text: "🍞🥦🍉🛒Supermarket Together🍞🥦🍉🛒",
    link: sdb + "2709570" },
  { text: "⛳🏎️🏁Turbo Golf Racing⛳🏎️🏁",
    link: sdb + "1324350/" },
  { text: "⚔️🛡️Valheim⚔️🛡️",
    link: sdb + "892970" },
  { text: "⛳🏌️Golf With Your Friends⛳🏌️",
    link: sdb + "431240" },
  { text: "🧦👨‍⚖️Guilty As Sock🧦👩‍⚖️",
    link: sdb + "3400930" },
  { text: "🏁🚗Pullback Racers🏁🚗",
    link: sdb + "3720110" },
  { text: "🎥👻Content Warning🎥👻",
    link: sdb + "2881650" },
  { text: "📃Dale & Dawson Stationery Supply📃",
    link: sdb + "2920570" },
  { text: "Try the whole night in 🖥️🎉LAN Party🖥️🎉",
    link: sdb + "2613480" },
  { text: "🎊🎮What the Pak?!🎊🎮",
    link: sdb + "2752710" },
  { text: "🎆🎇Fireworks Mania🎆🎇",
    link: sdb + "1079260" },
  { text: "🌌🍔Galaxy Burger🌌🍔",
    link: sdb + "2749770" },
  { text: "🐺🌊Iron Wolf (Submarine Sim)🐺🌊",
    link: sdb + "2530670" },
  { text: "🧱🧱🧱Brickadia🧱🧱🧱",
    link: sdb + "2199420" },
  { text: "🌳🌲🌳The Forest🌳🌲🌳",
    link: sdb + "242760" },
  { text: "📦R.E.P.O.📦",
    link: sdb + "3241660" },
  { text: "🔗🔗Chained🔗Together🔗🔗",
    link: sdb + "2567870" },
  { text: "⛰️🧗PEAK⛰️🧗",
    link: sdb + "3527290" }
];


console.log("OPTIONS initialized:", OPTIONS);